load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


# Needed by TensorFlow
http_archive(
  name = "io_bazel_rules_closure",
  sha256 = "7d206c2383811f378a5ef03f4aacbcf5f47fd8650f6abbc3fa89f3a27dd8b176",
  strip_prefix = "rules_closure-0.10.0",
  urls = [
    "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
    "https://github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
  ],
)

# TensorFlow
local_repository(
  name = "org_tensorflow",
  path = "/tensorflow_src",
)

# load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
# tf_workspace(tf_repo_name = "org_tensorflow")
load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")
tf_workspace3()

load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")
tf_workspace2()

load("@org_tensorflow//tensorflow:workspace1.bzl", "tf_workspace1")
tf_workspace1()

load("@org_tensorflow//tensorflow:workspace0.bzl", "tf_workspace0")
tf_workspace0()


http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "0f2de53628e848c1691e5729b515022f5a77369c76a09fbe55611e12731c90e3",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/2.0.1/rules_nodejs-2.0.1.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "npm_install")

# emscripten 2.0.14
#http_archive(
#    name = "emscripten",
#    sha256 = "e466cd47ddd4bf0acd645412fdf08eda6d232484e48e5a2643e08062a7a4cf56",
#    strip_prefix = "install",
#    url = "https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/fc5562126762ab26c4757147a3b4c24e85a7289e/wasm-binaries.tbz2",
#    build_file = "//emscripten_toolchain:emscripten.BUILD",
#    type = "tar.bz2",
#)

#npm_install(
#    name = "npm",
#    package_json = "@emscripten//:emscripten/package.json",
#    package_lock_json = "@emscripten//:emscripten/package-lock.json",
#)

# emscripten 2.0.20
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "emsdk",
    strip_prefix = "emsdk-c1589b55641787d55d53e883852035beea9aec3f/bazel",
    url = "https://github.com/emscripten-core/emsdk/archive/c1589b55641787d55d53e883852035beea9aec3f.tar.gz",
    sha256 = "7a58a9996b113d3e0675df30b5f17e28aa47de2e684a844f05394fe2f6f12e8e",
)


load("@emsdk//:deps.bzl", emsdk_deps = "deps")
emsdk_deps()

load("@emsdk//:emscripten_deps.bzl", emsdk_emscripten_deps = "emscripten_deps")
emsdk_emscripten_deps()


# opencv
new_local_repository(
    name = "opencv_for_emsdk2",
    path = "/opencv_for_emsdk2.0.14",
    build_file = "opencv.BUILD",
)

new_local_repository(
    name = "opencv_for_emsdk1",
    path = "/opencv_for_emsdk1.40.1",
    build_file = "opencv.BUILD",
)


# MediaPipe
local_repository(
  name="org_mediapipe",
  path = "/mediapipe",
)